### ISSUE TITLE
feature: maybe we can add a group and organize all those people's school

### ISSUE THREAD

**Issue by yangwenmai** [golang-design/history#2]

**Comment by changkun** [comment]
How specifically you mean? For instance, university?

**Comment by yangwenmai** [comment]
Yes

**Comment by changkun** [comment]
In the commit https://github.com/golang-design/history/commit/c32b5865d4d4c427c74c3f549dd643b42bb81e1b, I've added the alma mater for most of the Go core team. @yangwenmai Please double-check if this fulfills your interests. If yes, then we could close this as done; otherwise, we can continue work on more investigation for more committers.

**Comment by yangwenmai** [comment]
Thanks for your investigation.
