### ISSUE TITLE
Some of the links on scheduling are not working

### ISSUE THREAD

**Issue by helios741** [golang-design/history#23]
https://github.com/golang-design/history#scheduler
for example:
![image](https://user-images.githubusercontent.com/12036324/129892084-bcee6f1d-4daf-459a-8b72-88a43cb6c62d.png)
![image](https://user-images.githubusercontent.com/12036324/129892129-4d8275f8-29cb-4b72-b23f-cc7fc0f245f9.png)

**Comment by cristaloleg** [comment]
Works as expected for me 👀 and redirects to https://docs.google.com/document/d/1At2Ls5_fhJQ59kDK2DFVhFu3g5mATSXqqV5QrxinasI/edit

**Comment by changkun** [comment]
Thanks for the report. The link is provided as a shortened link of the google doc: golang.org/s/go15gomaxprocs.

I think this may be caused by the recent unstable migrations of the `golang.org` to `go.dev`.

See:
https://go-review.googlesource.com/c/website/+/342898
https://go-review.googlesource.com/c/website/+/343009
https://go-review.googlesource.com/c/website/+/342899
https://go-review.googlesource.com/c/website/+/342890
and more.

Also, I believe the inaccessible shortened links will be recovered when the migration is complete. Hence, close.
